#!/usr/bin/env python3
import fire
from mongofastlogger.logger import LogViewer, Logger


class Serpent(object):
    def make_view_and_log(self, name):
        self.logger = Logger(name)
        self.viewer = LogViewer(name)

    def search(self, tag, logger_name="logs"):
        self.make_view_and_log(logger_name)
        self.viewer.search_logs_by_tag(tag)

    def clear(self, logger_name="logs"):
        self.make_view_and_log(logger_name)
        self.viewer.clear_data()

    def log(self, tag, message, logger_name="logs"):
        self.make_view_and_log(logger_name)
        self.logger.log(tag, message)

    def view(self, logger_name="logs"):
        self.make_view_and_log(logger_name)
        self.viewer.view_log()

    def export(self, filename, logger_name="logs"):
        self.make_view_and_log(logger_name)
        self.viewer.export_log(filename)

    def last(self, metric, amount, logger_name="logs"):
        self.make_view_and_log(logger_name)
        self.viewer.check_by_time(metric, amount)


if __name__ == "__main__":
    fire.Fire(Serpent)
